### ISSUE TITLE
Variable naming

### ISSUE THREAD

**Issue by eduard93** [intersystems-ru/cos-guidelines#2]
So, whats the variable naming scheme?

```
set i
set CountIndex
```

**Comment by tsafin** [comment]
That was intentionally left unanswered - I'd prefer CamelCase for class names and function names, and smallCase for variables. But seems like I've bad luck convincing to use it Sergey Kudinov and Dmitry Zasypkin. So unless there is consensus we could not prefer anything.

"Use the reasonable name convention which is consistent across hierarchy" could be the only recommendation.
