### ISSUE TITLE
Why statements in all lower-case

### ISSUE THREAD

**Issue by eduard93** [intersystems-ru/cos-guidelines#4]
Let's make first letter capital

```
If (expression) {
  Do ##class(Sample).%New(initexpresion)
   For i=1:1:10 {
    Write something,!
  }
 }
```

look better than

```
 if (expression) {
  do ##class(Sample).%New(initexpresion)
   for i=1:1:10 {
    write something,!
  }
 }

```

**Comment by tsafin** [comment]
Those styles both consistent and ight be recommended equally. But here is my reasoning why I recommend lower-case:
- you should select either you want to be similar to Basic or similar to C/C++.

[I hope you will prefer to be familiar to C/C++ developers in general] In either cae those styles are kbotth consistent and igt be considered legal alternatives.

**Comment by eduard93** [comment]
Yeah, I agree that the most important part is consistency inside of a project. Some minutiae may differ from the rules suggested, but it must be consistent everywhere.
