### ISSUE TITLE
Short class naming inside package

### ISSUE THREAD

**Issue by eduard93** [intersystems-ru/cos-guidelines#5]
I propose mandatory full name of class (except %Library package) 

```
Set obj = do ##class(Sample.Person).%New(initexpresion)
```

instead of

```
Set obj = do ##class(Person).%New(initexpresion)
```

**Comment by tsafin** [comment]
Agreed that fully expanded class-names should be used. Though in general I'd prefer we to fully qualify even %Library classes.

**Comment by tsafin** [comment]
I've changed my ind and agree on short name for %-classes (because in majority of my code I did not write it fully-quialified till the moment :) )
I'll put this to optional part though, because I don't want to be _so much_ restrictive.
